
nc : 1
names : 
  polyps : 0

#----------------------- 
# Model architecture One of ['tiny', 's', 'm', 'l', 'x']
#-----------------------
version: 'n'

#-----------------------
# data path
#-----------------------
train: /Users/LAP60311/work/Contract/poc_ACB_data/data/train/images
val: /Users/LAP60311/work/Contract/poc_ACB_data/data/val/images
# test: /home/s/sonnh/polyp_data/test/images

#-----------------------
# data configs
#-----------------------
input_size : 640
max_objects : 100
model_dir : ''
batch_size : 16
epochs : 100
resume : False

optimizer :
  type : Adam
  base_lr : 1e-3
  end_lr : 1e-5
  warmup_lr : 2e-5
  warmup_steps : 10000