
nc : 1
names : 
  polyps : 0
  adenomatous : 0
  hyperplastic : 0

#----------------------- 
# Model architecture One of ['tiny', 's', 'm', 'l', 'x']
#-----------------------
version: 'n'

#-----------------------
# Data path
#-----------------------
train : D:/VNG/E2EObjectDetection/PolypsSet_converted/train2019/images
val : D:/VNG/E2EObjectDetection/PolypsSet_converted/val2019/images
test: D:/VNG/E2EObjectDetection/PolypsSet_converted/test2019/images

#-----------------------
# Training configs
#-----------------------
gpu : '0'
input_size : 640
batch_size : 16
epochs : 100
optimizer :
  type : Adam
  base_lr : 0.001 #1e-3
  end_lr : 0.00001 #1e-5
  warmup_lr : 0.00002 #2e-5
  warmup_steps : 10000

max_boxes : 100
save_dir : 'save_dir/test'
save_period: 5
resume : False
resume_checkpoint : ''
